"""L6 -- Skills, Tools & Action Runtime (Act).

Exposes the existing ESG system's service operations as a discoverable tool
catalogue and executes them on behalf of the agent. The executable capability
here is the metric-computation service of the ESG Metric System, reached
through whichever adapter L6 was constructed with.

Boundary (Section IV-C): L6 separates the decision to invoke a capability,
coordinated by L3, from the mechanism that authorizes and executes it. The
computation remains an explicit deterministic service operation and is never
generated by the model (Section V-B).

Resource-specific authorization is enforced here rather than at L2: L2
establishes whether a principal may reach the agentic system at all, while L6
decides whether this principal may invoke this capability on this resource
(Section IV-E).
"""

from typing import Any, Dict, List, Optional


class ActionRuntime:
    RESPONSIBILITY = "L6"

    def __init__(self, adapter, require_approval: bool = False):
        self._esg = adapter
        self._require_approval = require_approval
        self._registry: Dict[str, Dict[str, Any]] = {
            "compute_metric": {
                "description": "Execute an ESG metric calculation model for a "
                               "company and reporting year",
                "params": ["metric", "company", "year", "industry"],
                "consequential": False,     # bounded analytical read
                "entitlement": "esg.metric.compute",
                "realizes": "/api/CSservice/calculate",
            },
        }

    # -- discovery ---------------------------------------------------------
    def list_tools(self) -> List[str]:
        return sorted(self._registry)

    def describe(self, tool: str) -> Dict[str, Any]:
        return self._registry[tool]

    @property
    def mechanism(self) -> str:
        return getattr(self._esg, "mechanism", "unknown")

    # -- validation and authorization --------------------------------------
    def validate(self, tool: str, args: Dict[str, Any]) -> None:
        if tool not in self._registry:
            raise ValueError(f"unknown tool: {tool}")
        missing = [p for p in self._registry[tool]["params"] if not args.get(p)]
        if missing:
            raise ValueError(f"missing required arguments: {', '.join(missing)}")

    def authorize(self, tool: str, principal: Optional[Dict[str, Any]]) -> None:
        """Resource-specific authorization, distinct from L2 system access."""
        needed = self._registry[tool]["entitlement"]
        held = (principal or {}).get("entitlements", [])
        if needed not in held:
            raise PermissionError(
                f"principal lacks entitlement '{needed}' for {tool}")

    def approval_required(self, tool: str) -> bool:
        """Conditional capability: only consequential actions need approval."""
        return self._require_approval and self._registry[tool]["consequential"]

    # -- execution ---------------------------------------------------------
    def invoke(self, tool: str, principal: Optional[Dict[str, Any]] = None,
               **args: Any) -> Dict[str, Any]:
        self.validate(tool, args)
        self.authorize(tool, principal)
        if self.approval_required(tool):
            raise PermissionError(f"{tool} requires human approval")

        r = self._esg.calculate(args["industry"], args["company"],
                                args["year"], [args["metric"]])
        if r.get("status") != "success":
            # the ESG service reports its reason in different fields
            reason = (r.get("error") or r.get("message")
                      or r.get("display_value") or "calculation failed")
            return {"status": "error", "error": str(reason).lstrip("\u274c ")}

        return {
            "status": "success",
            "value": r.get("value"),
            "display_value": r.get("display_value"),
            "unit": r.get("unit"),
            "provenance": {
                "model": r.get("model_name"),
                "equation": r.get("model_equation"),
                "inputs": r.get("input_values"),
                "input_dataset_variables": r.get("input_dataset_variables"),
                "implementation": r.get("implementation"),
                "realized_by": self._registry[tool]["realizes"],
                "mechanism": self.mechanism,
            },
        }
