"""L6 -- Tool & Action Runtime (Act).

Registers the executable capabilities available to the agent, and validates,
authorizes and executes each invocation:

  compute_metric       ESG metric computation (existing ESG system, via MCP)
  portfolio_intensity  portfolio carbon intensity (portfolio service, via MCP)
  propose_rebalance    a portfolio reweighting -- consequential, so it passes
                       an approval gate before it takes effect

Boundary (invariant I1): L6 separates the decision to invoke a capability,
coordinated by L3, from the mechanism that authorizes and executes it. Values
are produced by deterministic services and never generated by the model.

Resource-specific authorization is enforced here rather than at L2 (invariant
I3): L2 establishes who may reach the agentic system at all, while L6 decides
whether this principal may invoke this capability, and whether a proposal may
be approved by this approver.
"""

import uuid
from typing import Any, Dict, List, Optional

# Proposals awaiting a decision. Held by L6 because the approval gate is an L6
# capability; a deployment would persist these.
PROPOSALS: Dict[str, Dict[str, Any]] = {}


class ActionRuntime:
    RESPONSIBILITY = "L6"

    REGISTRY: Dict[str, Dict[str, Any]] = {
        "compute_metric": {
            "params": ["metric", "company", "year", "industry"],
            "entitlement": "esg.metric.compute", "consequential": False,
            "realizes": "MCP esg-compute -> /api/CSservice/calculate"},
        "portfolio_intensity": {
            "params": ["holdings", "year"],
            "entitlement": "esg.portfolio.analyze", "consequential": False,
            "realizes": "MCP esg-portfolio -> portfolio_intensity"},
        "propose_rebalance": {
            "params": ["holdings", "target_weights", "year"],
            "entitlement": "esg.portfolio.propose", "consequential": True,
            "realizes": "MCP esg-portfolio -> evaluate_rebalance"},
    }
    APPROVE_ENTITLEMENT = "esg.portfolio.approve"

    def __init__(self, compute, portfolio=None, require_approval: bool = True):
        self._compute = compute
        self._portfolio = portfolio
        self._require_approval = require_approval

    @property
    def mechanism(self) -> str:
        return getattr(self._compute, "mechanism", "unknown")

    def list_tools(self) -> List[str]:
        return sorted(self.REGISTRY)

    # -- validation and authorization --------------------------------------
    def validate(self, tool: str, args: Dict[str, Any]) -> None:
        if tool not in self.REGISTRY:
            raise ValueError(f"unknown tool: {tool}")
        missing = [p for p in self.REGISTRY[tool]["params"]
                   if args.get(p) in (None, "", [])]
        if missing:
            raise ValueError(f"missing required arguments: {', '.join(missing)}")

    @staticmethod
    def _require(entitlement: str, principal: Optional[Dict[str, Any]],
                 what: str) -> None:
        if entitlement not in (principal or {}).get("entitlements", []):
            raise PermissionError(
                f"principal lacks entitlement '{entitlement}' for {what}")

    def authorize(self, tool: str, principal: Optional[Dict[str, Any]]) -> None:
        """Resource-specific authorization, distinct from L2 system access."""
        self._require(self.REGISTRY[tool]["entitlement"], principal, tool)

    # -- execution ---------------------------------------------------------
    def invoke(self, tool: str, principal: Optional[Dict[str, Any]] = None,
               **args: Any) -> Dict[str, Any]:
        self.validate(tool, args)
        self.authorize(tool, principal)
        return getattr(self, "_" + tool)(principal, **args)

    def _compute_metric(self, principal, metric, company, year, industry):
        r = self._compute.calculate(industry, company, year, [metric])
        if r.get("status") != "success":
            reason = (r.get("error") or r.get("error_message")
                      or r.get("message") or r.get("display_value")
                      or "calculation failed")
            return {"status": "error", "company": company, "year": str(year),
                    "error": str(reason).lstrip("❌ ")}
        return {
            "status": "success", "company": company, "year": str(year),
            "value": r.get("value"), "display_value": r.get("display_value"),
            "unit": r.get("unit"),
            "provenance": {
                "model": r.get("model_name"),
                "equation": r.get("model_equation"),
                "inputs": r.get("input_values"),
                "input_dataset_variables": r.get("input_dataset_variables"),
                "implementation": r.get("implementation"),
                "realized_by": self.REGISTRY["compute_metric"]["realizes"],
            },
        }

    def _portfolio_intensity(self, principal, holdings, year, previous=None):
        return {"status": "success",
                **self._portfolio.portfolio_intensity(holdings, year, previous)}

    def _propose_rebalance(self, principal, holdings, target_weights, year):
        evaluation = self._portfolio.evaluate_rebalance(holdings,
                                                        target_weights, year)
        if not evaluation.get("valid"):
            return {"status": "error", "error": evaluation.get("error")}
        if not (self._require_approval
                and self.REGISTRY["propose_rebalance"]["consequential"]):
            return {"status": "success", **evaluation}
        pid = uuid.uuid4().hex[:8]
        PROPOSALS[pid] = {"proposal_id": pid, "status": "pending_approval",
                          "proposed_by": (principal or {}).get("subject"),
                          "evaluation": evaluation}
        return {"status": "pending_approval", "proposal_id": pid,
                "approval_required_from": "portfolio manager",
                **evaluation}

    # -- approval gate -----------------------------------------------------
    def decide(self, proposal_id: str, approve: bool,
               principal: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Record an approval decision on a pending proposal.

        The approver must hold the approval entitlement and must not be the
        principal on whose behalf the proposal was made (four-eyes rule).
        """
        p = PROPOSALS.get(proposal_id)
        if p is None:
            raise ValueError(f"unknown proposal: {proposal_id}")
        if p["status"] != "pending_approval":
            raise ValueError(f"proposal {proposal_id} is already {p['status']}")
        self._require(self.APPROVE_ENTITLEMENT, principal,
                      f"approving proposal {proposal_id}")
        approver = (principal or {}).get("subject")
        if approver == p["proposed_by"]:
            raise PermissionError("a proposal cannot be approved by the "
                                  "principal who requested it")
        p["status"] = "approved" if approve else "rejected"
        p["decided_by"] = approver
        p["note"] = ("recorded as an approved rebalancing instruction; no "
                     "trading system is connected, so no order is placed"
                     if approve else "proposal rejected; weights unchanged")
        return dict(p)
