"""L6 -- Tool & Action Runtime (Act).

Registers the executable capabilities available to the agent, and validates,
authorizes and executes each invocation:

  compute_metric       ESG metric computation (existing ESG system, via MCP)
  portfolio_intensity  portfolio carbon intensity (portfolio service, via MCP)
  check_trade          pre-trade compliance check against the fund mandate
  submit_trade         a trade instruction -- consequential: L6 re-checks
                       compliance itself; a compliant trade is cleared, a
                       breaching one is held for a compliance override

Boundary (invariant I1): L6 separates the decision to invoke a capability,
coordinated by L3, from the mechanism that authorizes and executes it. Values
are produced by deterministic services and never generated by the model.

Resource-specific authorization is enforced here rather than at L2 (invariant
I3): L2 establishes who may reach the agentic system at all, while L6 decides
whether this principal may invoke this capability, and whether an override may
be approved by this approver.
"""

import uuid
from typing import Any, Dict, List, Optional

# Submitted trades. Held by L6 because the approval gate is an L6 capability;
# a deployment would persist these and hand cleared trades to an order
# management system. None is connected here, so no order is ever placed.
TRADES: Dict[str, Dict[str, Any]] = {}


class ActionRuntime:
    RESPONSIBILITY = "L6"

    REGISTRY: Dict[str, Dict[str, Any]] = {
        "compute_metric": {
            "params": ["metric", "company", "year", "industry"],
            "entitlement": "esg.metric.compute", "consequential": False,
            "realizes": "MCP esg-compute -> /api/CSservice/calculate"},
        "portfolio_intensity": {
            "params": ["holdings", "year"],
            "entitlement": "esg.portfolio.analyze", "consequential": False,
            "realizes": "MCP esg-portfolio -> portfolio_intensity"},
        "check_trade": {
            "params": ["fund", "holdings", "trades", "year"],
            "entitlement": "esg.portfolio.analyze", "consequential": False,
            "realizes": "MCP esg-portfolio -> check_trade"},
        "submit_trade": {
            "params": ["fund", "holdings", "trades", "year"],
            "entitlement": "trade.submit", "consequential": True,
            "realizes": "MCP esg-portfolio -> check_trade; approval gate"},
    }
    OVERRIDE_ENTITLEMENT = "trade.override.approve"

    def __init__(self, compute, portfolio=None):
        self._compute = compute
        self._portfolio = portfolio

    @property
    def mechanism(self) -> str:
        return getattr(self._compute, "mechanism", "unknown")

    # -- validation and authorization --------------------------------------
    def validate(self, tool: str, args: Dict[str, Any]) -> None:
        if tool not in self.REGISTRY:
            raise ValueError(f"unknown tool: {tool}")
        missing = [p for p in self.REGISTRY[tool]["params"]
                   if args.get(p) in (None, "", [])]
        if missing:
            raise ValueError(f"missing required arguments: {', '.join(missing)}")

    @staticmethod
    def _require(entitlement: str, principal: Optional[Dict[str, Any]],
                 what: str) -> None:
        if entitlement not in (principal or {}).get("entitlements", []):
            raise PermissionError(
                f"principal lacks entitlement '{entitlement}' for {what}")

    def authorize(self, tool: str, principal: Optional[Dict[str, Any]]) -> None:
        """Resource-specific authorization, distinct from L2 system access."""
        self._require(self.REGISTRY[tool]["entitlement"], principal, tool)

    # -- execution ---------------------------------------------------------
    def invoke(self, tool: str, principal: Optional[Dict[str, Any]] = None,
               **args: Any) -> Dict[str, Any]:
        self.validate(tool, args)
        self.authorize(tool, principal)
        return getattr(self, "_" + tool)(principal, **args)

    def _compute_metric(self, principal, metric, company, year, industry):
        r = self._compute.calculate(industry, company, year, [metric])
        if r.get("status") != "success":
            reason = (r.get("error") or r.get("error_message")
                      or r.get("message") or r.get("display_value")
                      or "calculation failed")
            return {"status": "error", "company": company, "year": str(year),
                    "error": str(reason).lstrip("❌ ")}
        return {
            "status": "success", "company": company, "year": str(year),
            "value": r.get("value"), "display_value": r.get("display_value"),
            "unit": r.get("unit"),
            "provenance": {
                "model": r.get("model_name"),
                "equation": r.get("model_equation"),
                "inputs": r.get("input_values"),
                "input_dataset_variables": r.get("input_dataset_variables"),
                "implementation": r.get("implementation"),
                "realized_by": self.REGISTRY["compute_metric"]["realizes"],
            },
        }

    def _portfolio_intensity(self, principal, holdings, year, previous=None):
        return {"status": "success",
                **self._portfolio.portfolio_intensity(holdings, year, previous)}

    def _check_trade(self, principal, fund, holdings, trades, year):
        r = self._portfolio.check_trade(fund, holdings, trades, year)
        if not r.get("valid"):
            return {"status": "error", "error": r.get("error")}
        return {"status": "success", **r}

    def _submit_trade(self, principal, fund, holdings, trades, year,
                      justification=None):
        # Action policy: compliance is re-checked here, not taken from L3.
        check = self._portfolio.check_trade(fund, holdings, trades, year)
        if not check.get("valid"):
            return {"status": "error", "error": check.get("error")}
        tid = uuid.uuid4().hex[:8]
        compliant = check["compliant"]
        record = {"trade_id": tid,
                  "status": "cleared" if compliant else "pending_override",
                  "submitted_by": (principal or {}).get("subject"),
                  "justification": justification, "check": check}
        record["note"] = (
            "cleared by pre-trade compliance and recorded for order "
            "management; no order management system is connected, so no "
            "order is placed" if compliant else
            "breaches the fund mandate; held until a compliance officer "
            "approves an override")
        TRADES[tid] = record
        return {"status": record["status"], "trade_id": tid,
                "note": record["note"], "compliant": compliant,
                "breaches": check["breaches"],
                "waci_before": check["waci_before"],
                "waci_after": check["waci_after"],
                "trades": check["trades"]}

    # -- approval gate -----------------------------------------------------
    def decide(self, trade_id: str, approve: bool,
               principal: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Record a compliance officer's decision on a held trade.

        The approver must hold the override entitlement and must not be the
        principal who submitted the trade (four-eyes rule).
        """
        t = TRADES.get(trade_id)
        if t is None:
            raise ValueError(f"unknown trade: {trade_id}")
        if t["status"] != "pending_override":
            raise ValueError(f"trade {trade_id} is {t['status']}, "
                             "not awaiting an override")
        self._require(self.OVERRIDE_ENTITLEMENT, principal,
                      f"overriding trade {trade_id}")
        approver = (principal or {}).get("subject")
        if approver == t["submitted_by"]:
            raise PermissionError("an override cannot be approved by the "
                                  "principal who submitted the trade")
        t["status"] = "override_approved" if approve else "rejected"
        t["decided_by"] = approver
        t["note"] = ("override approved and recorded for order management; "
                     "no order is placed" if approve
                     else "override rejected; trade not executed")
        return {k: t[k] for k in ("trade_id", "status", "submitted_by",
                                  "decided_by", "note")}
